CREATE TABLE IF NOT EXISTS BabyNames (
    Id INTEGER PRIMARY KEY,
    Name TEXT NOT NULL,
    Gender INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Users (
    Id INTEGER PRIMARY KEY,
    EmailAddress TEXT NOT NULL,
    FullName TEXT NOT NULL,
    PictureUri TEXT NULL
);

CREATE TABLE IF NOT EXISTS UserVotes (
    UserId INTEGER NOT NULL,
    NameId INTEGER NOT NULL,
    Vote INTEGER NOT NULL,
    PRIMARY KEY (UserId, NameId),
    FOREIGN KEY(UserId) REFERENCES Users(Id),
    FOREIGN KEY(NameId) REFERENCES BabyNames(Id)
);
